logging:
  level:
    org.springframework: INFO
    org.thymeleaf: INFO
    com.onestop: DEBUG
#REST超时配置
#httpclient:
#  connect-timeout: 60000默认值
#  read-timeout: 30000默认值
#token配置
os:
  mail:
    # 开启邮件工具类
    isopen: true
    # 邮件服务器的SMTP地址 默认：126
#    host: smtp.126.com
    # 邮件服务器的SMTP端口 默认：25
#    port: 25
    # 发件人（必须正确，否则发送失败）
    from:
    # 用户名（注意：如果使用foxmail邮箱，此处user为qq号）
    user:
    # 密码（注意，某些邮箱需要为SMTP服务单独设置密码，详情查看相关帮助）
    pass:
    #使用 STARTTLS安全连接，STARTTLS是对纯文本通信协议的扩展。
#    starttlsEnable: true
    # 使用SSL安全连接
#    sslEnable: false
  token:
    # 开启邮件工具类
    isopen: true
    # 私钥 16位
#    secret: abcdefg1234567890
    # 过期时间 默认：120分钟
#    expireTimeInMinutes: 120

