logging:
  level:
    org.springframework: INFO
    cn.onestop: DEBUG

os:
  rocketmq:
    # 开启短信工具类
    enabled: true
    accessKey: XXX
    secretKey: XXX
    nameSrvAddr: XXX
    # 普通消息
    topic: XXX
    groupId: XXX
    tag: *
    # 顺序消息
    orderTopic: XXX
    orderGroupId: XXX
    orderTag: *