os:
  oss:
    # 开启oss工具类
    enabled: true
    # AccessKey ID
    accessKeyId: xxxx
    # AccessKey Secret
    accessKeySecret: xxxx
    # endpoint
    endpoint: xxxx
    # bucketName
    bucketName: xxxx