logging:
  level:
    org.springframework: INFO
    com.onestop: DEBUG
os:
  azure:
    storage:
      # 开启邮件工具类
      isopen: true
      # 连接字符串
      connectionString:
      # 容器名称必须为小写，默认值：os-storage
#      containerName:
      # token超时时长，默认120分钟
#      expireTimeInMinutes: 120