logging:
  level:
    org.springframework.web: info
    cn.binarywang.wx.miniapp: debug
    com.onestop: debug
os:
  wxmp:
    # 开启小程序配置
    isopen: true
    appid: wx930d31e7062a95ea
    secret: 1eac705cf3da3b7605dd8c375d2b8513
    token: cloud
    aesKey: SRXP07cF633daFYh7jasMRDHYMKjANeEQe8kwrfWB5p
    #服务器域名
    serverHost: http://azwx.ithelpdesk.cn
    #后台配置
    serverPath: /wxMp
    #后台api路径配置
    apiPath: ${wx.serverPath}/api
    #前端路径配置
    uiPath: ${wx.serverHost}/wxui
